name: Announce

on:
  workflow_dispatch:
  schedule:
    #       ┌──────────────── minute (0 - 59)
    #       │ ┌────────────── hour (0 - 23)
    #       │ │ ┌──────────── day of the month (1 - 31)
    #       │ │ │ ┌────────── month (1 - 12 or JAN-DEC)
    #       │ │ │ │ ┌──────── day of the week (0 - 6 or SUN-SAT)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       * * * * *
    - cron: 0 0 9 * *

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
      - name: Download Binary
        run: curl -sLO https://github.com/$GITHUB_REPOSITORY/releases/download/latest/Bot

      - name: Make Binary Executable
        run: chmod +x Bot

      - name: Announce Bill
        run: ./Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PAYLAH_LINK: ${{ secrets.PAYLAH_LINK }}
          PROXY_LINK: ${{ secrets.PROXY_LINK }}
