name: Deploy

on:
  push:
    branches: [main]
    paths:
      - '**.ts'
      - .github/workflows/main.yml
      - tsconfig.json
      - package.json
      - bun.lockb

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint

      - name: Test
        run: bun test

      - name: Build
        run: bun run build --minify

      - name: Deploy
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: latest
          RELEASE_TITLE: Build
          RELEASE_ASSET: dist/Bot
        run: |
          gh release delete $RELEASE_TAG -y || true
          gh release create $RELEASE_TAG -t $RELEASE_TITLE || true
          gh release upload $RELEASE_TAG $RELEASE_ASSET --clobber
